<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Build</name>
   <tag></tag>
   <elementGuidId>c5d068cb-0e53-43f5-aeed-9e41b8709f05</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>swal2-confirm btn btn_blue</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Build</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js no-touch cssanimations csstransitions ng-scope remodal-is-locked&quot;]/body[@class=&quot;pushable swal2-in&quot;]/div[@class=&quot;swal2-container swal2-in&quot;]/div[@class=&quot;swal2-modal animated fadeIn swal2-noanimation&quot;]/button[@class=&quot;swal2-confirm btn btn_blue&quot;]</value>
   </webElementProperties>
</WebElementEntity>
