<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>h2_Success</name>
   <tag></tag>
   <elementGuidId>c14ff70a-3f19-42fd-bf4a-8cbf940f3bf5</elementGuidId>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>h2</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Success</value>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;js no-touch cssanimations csstransitions ng-scope remodal-is-locked&quot;]/body[@class=&quot;pushable swal2-in&quot;]/div[@class=&quot;swal2-container swal2-in&quot;]/div[@class=&quot;swal2-modal animated fadeIn swal2-noanimation&quot;]/h2[1]</value>
   </webElementProperties>
</WebElementEntity>
